Added example gst/gtk app from the web...
This requires a LOT of crap to be installed to get it to work, none of which
appeared to be pip installable. I ended up installing the F18 package
gstreamer-python and then manually copying the following into my virtualenv
from /usr/lib64/python2.7/site-packages/:

cairo
glib
gobject
gst-0.10
gtk-2.0
pygst.*
pygtk.*

Note that the file path for the app needs to be aboslute to get it to run,
otherwise it'll just fail silently.

I think the equivalent gst command line is:
gst-launch-0.10 playbin uri=file://<abs_path>

If you get the path wrong on the command line, you can see where gstreamer gets
stuck:
  Setting pipeline to PAUSED ...
  ERROR: Pipeline doesn't want to pause.
  ERROR: from element /GstPlayBin:playbin0/GstGioSrc:source: Could not open
  resource for reading.
  Additional debug info:
  gstgiosrc.c(324): gst_gio_src_get_stream ():
  /GstPlayBin:playbin0/GstGioSrc:source:
  Could not open location file://test.ogg for reading: Operation not supported
  Setting pipeline to NULL ...
  Freeing pipeline ...